name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: |
          uv pip install --system -e ".[dev]"

      - name: Run pre-commit (all files)
        uses: pre-commit/action@v3.0.1

      - name: Run tests
        run: pytest -v
